blockchain:
  # 日志存放路径
  log_path: "./"
network:
  listen_host: "210.32.136.66"
  # 本地监听端口
  listen_port: "9002"
  # 节点组唯一标识名称(如果节点间名称不同会找不到网络)
  rendezvous_string: "miniDVPN-blockchain"
  # 网络传输流的协议id(如果节点间id不同发送不了数据)
  protocol_id: "/miniDVPN/0.0.1"
interface:
  name: "peer1"
  
  address: "10.1.1.1"

